export default theme => ({
  'checkbox--wrapper': {
    display: 'inline-block',
    cursor: 'pointer',
    fontSize: 14,
  },
  checkbox: {
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    outline: 'none',
    display: 'inline-block',
    lineHeight: 1,
    position: 'relative',
    verticalAlign: 'text-bottom',
    '& + span': {
      paddingLeft: 8,
      paddingRight: 8,
    },
    '& input': {
      position: 'absolute',
      left: 0,
      zIndex: 1,
      cursor: 'pointer',
      opacity: 0,
      top: 0,
      bottom: 0,
      right: 0,
      width: '100%',
      height: '100%',
    },
  },
  checkbox__checked: {
    '& $checkbox--inner': {
      backgroundColor: theme['brand-primary'],
      borderColor: theme['brand-primary'],
      '&:after': {
        transform: 'rotate(45deg) scale(1)',
        position: 'absolute',
        left: 4,
        top: 1,
        display: 'table',
        width: 4,
        height: 8,
        border: '2px solid #fff',
        borderTop: 0,
        borderLeft: 0,
        content: '""',
        transition: 'all 0.2s cubic-bezier(0.12, 0.4, 0.29, 1.46) 0.1s',
      },
    },
  },
  checkbox__disabled: {
    '& + span': {
      color: 'rgba(0, 0, 0, 0.25)',
      cursor: 'not-allowed',
    },
    '& input': {
      cursor: 'not-allowed',
    },
    '& $checkbox--inner': {
      backgroundColor: '#f5f5f5',
      borderColor: '#e6e6e6',
      '&:after': {
        animationName: 'none',
        borderColor: 'rgba(0, 0, 0, 0.25)',
      },
    },
  },
  'checkbox--inner': {
    position: 'relative',
    top: 0,
    left: 0,
    display: 'block',
    width: 14,
    height: 14,
    border: '1px solid #e6e6e6',
    borderRadius: 3,
    backgroundColor: '#fff',
    transition: 'all 0.3s',
    '&:after': {
      transform: 'rotate(45deg) scale(0)',
      position: 'absolute',
      left: 4,
      top: 1,
      display: 'table',
      width: 4,
      height: 8,
      border: '2px solid #fff',
      borderTop: 0,
      borderLeft: 0,
      content: '""',
      transition: 'all 0.1s cubic-bezier(0.71, -0.46, 0.88, 0.6)',
    },
  },
  'checkbox--group': {
    display: 'inline-block',
    fontSize: 12,
  },
  radio: {
    outline: 'none',
    lineHeight: 1,
    verticalAlign: 'text-bottom',
    display: 'inline-block',
    position: 'relative',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    '& + span': {
      paddingLeft: 8,
      paddingRight: 8,
    },
    '& input': {
      position: 'absolute',
      left: 0,
      zIndex: 1,
      cursor: 'pointer',
      opacity: 0,
      top: 0,
      bottom: 0,
      right: 0,
    },
  },
  radio__disabled: {
    '& + span': {
      color: 'rgba(0, 0, 0, 0.25)',
      cursor: 'not-allowed',
    },
    '& input': {
      cursor: 'not-allowed',
    },
    '& $radio--inner': {
      borderColor: '#d9d9d9 !important',
      backgroundColor: '#f7f7f7',
      '&:after': {
        backgroundColor: '#ccc',
      },
    },
  },
  radio__checked: {
    '& $radio--inner': {
      borderColor: theme['brand-primary'],
      '&:after': {
        transform: 'scale(1)',
        opacity: 1,
        transition: 'all 0.3s cubic-bezier(0.78, 0.14, 0.15, 0.86)',
      },
    },
  },
  'radio--inner': {
    position: 'relative',
    top: 0,
    left: 0,
    display: 'block',
    width: 14,
    height: 14,
    borderRadius: 14,
    border: '1px solid #d9d9d9',
    backgroundColor: '#fff',
    transition: 'all 0.3s',
    '&:after': {
      position: 'absolute',
      width: 8,
      height: 8,
      left: 3,
      top: 3,
      borderRadius: 4,
      display: 'table',
      borderTop: 0,
      borderLeft: 0,
      content: '""',
      backgroundColor: theme['brand-primary'],
      opacity: 0,
      transform: 'scale(0)',
      transition: 'all 0.3s cubic-bezier(0.78, 0.14, 0.15, 0.86)',
    },
  },
  'radio--wrapper': {
    fontSize: 12,
    marginRight: 8,
  },
  'radio-button--wrapper': {
    margin: 0,
    height: 28,
    lineHeight: '26px',
    color: 'rgba(0, 0, 0, 0.65)',
    display: 'inline-block',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    border: '1px solid #d9d9d9',
    borderLeft: 0,
    background: '#fff',
    padding: '0 16px',
    '&:hover': {
      color: theme['brand-primary'],
    },
    '&:first-child': {
      borderRadius: '4px 0 0 4px',
      borderLeft: '1px solid #d9d9d9',
    },
    '&:last-child': {
      borderRadius: '0 4px 4px 0',
    },
  },
  'radio-button--wrapper__checked': {
    background: '#fff',
    borderColor: theme['brand-primary'],
    backgroundColor: theme['brand-primary'],
    color: '#fff',
    boxShadow: `-1px 0 0 0 ${theme['brand-primary']}`,
    '&:first-child': {
      borderColor: theme['brand-primary'],
      boxShadow: 'none !important',
    },
  },
  'radio-button--wrapper__disabled': {
    cursor: 'not-allowed',
    borderColor: '#d9d9d9!important',
    backgroundColor: '#f7f7f7',
    color: 'rgba(0, 0, 0, 0.25)!important',
    '&.radio-button--wrapper__checked': {
      color: '#fff',
      backgroundColor: '#e6e6e6',
      borderColor: '#d9d9d9',
      boxShadow: 'none',
    },
  },
  'radio-button': {
    marginLeft: 0,
    display: 'block',
    width: 0,
    height: 0,
    '& input': {
      opacity: 0,
      width: 0,
      height: 0,
    },
  },
});
